# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FILE/at7_img_ex11_uvc/UVC_OV5640/uvc_ov5640/uvc_ov5640.srcs/sources_1/ip/fifo_generator_2/fifo_generator_2.xci
# IP: The module: 'fifo_generator_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FILE/at7_img_ex11_uvc/UVC_OV5640/uvc_ov5640/uvc_ov5640.srcs/sources_1/ip/fifo_generator_2/fifo_generator_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/FILE/at7_img_ex11_uvc/UVC_OV5640/uvc_ov5640/uvc_ov5640.srcs/sources_1/ip/fifo_generator_2/fifo_generator_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/FILE/at7_img_ex11_uvc/UVC_OV5640/uvc_ov5640/uvc_ov5640.srcs/sources_1/ip/fifo_generator_2/fifo_generator_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/FILE/at7_img_ex11_uvc/UVC_OV5640/uvc_ov5640/uvc_ov5640.srcs/sources_1/ip/fifo_generator_2/fifo_generator_2.xci
# IP: The module: 'fifo_generator_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FILE/at7_img_ex11_uvc/UVC_OV5640/uvc_ov5640/uvc_ov5640.srcs/sources_1/ip/fifo_generator_2/fifo_generator_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/FILE/at7_img_ex11_uvc/UVC_OV5640/uvc_ov5640/uvc_ov5640.srcs/sources_1/ip/fifo_generator_2/fifo_generator_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/FILE/at7_img_ex11_uvc/UVC_OV5640/uvc_ov5640/uvc_ov5640.srcs/sources_1/ip/fifo_generator_2/fifo_generator_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
