# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FILE/at7_img_ex11_uvc/UVC_OV5640/uvc_ov5640/uvc_ov5640.srcs/sources_1/ip/v_demosaic_0/v_demosaic_0.xci
# IP: The module: 'v_demosaic_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FILE/at7_img_ex11_uvc/UVC_OV5640/uvc_ov5640/uvc_ov5640.srcs/sources_1/ip/v_demosaic_0/v_demosaic_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_demosaic_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/FILE/at7_img_ex11_uvc/UVC_OV5640/uvc_ov5640/uvc_ov5640.srcs/sources_1/ip/v_demosaic_0/v_demosaic_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_demosaic_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/FILE/at7_img_ex11_uvc/UVC_OV5640/uvc_ov5640/uvc_ov5640.srcs/sources_1/ip/v_demosaic_0/v_demosaic_0.xci
# IP: The module: 'v_demosaic_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FILE/at7_img_ex11_uvc/UVC_OV5640/uvc_ov5640/uvc_ov5640.srcs/sources_1/ip/v_demosaic_0/v_demosaic_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_demosaic_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/FILE/at7_img_ex11_uvc/UVC_OV5640/uvc_ov5640/uvc_ov5640.srcs/sources_1/ip/v_demosaic_0/v_demosaic_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_demosaic_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
