set_property IOSTANDARD LVCMOS18 [get_ports sys_clk_i]
set_property PACKAGE_PIN D27 [get_ports sys_clk_i]

#set_property IOSTANDARD LVTTL [get_ports ext_rst_n]
#set_property PACKAGE_PIN T2 [get_ports ext_rst_n]

set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN T21 [get_ports {led[0]}]




#USB3
set_property PACKAGE_PIN AC21 [get_ports {fx3_db[0]}]
set_property PACKAGE_PIN AC20 [get_ports {fx3_db[1]}]
set_property PACKAGE_PIN AE23 [get_ports {fx3_db[2]}]
set_property PACKAGE_PIN AA23 [get_ports {fx3_db[3]}]
set_property PACKAGE_PIN AE24 [get_ports {fx3_db[4]}]
set_property PACKAGE_PIN AF23 [get_ports {fx3_db[5]}]
set_property PACKAGE_PIN AC22 [get_ports {fx3_db[6]}]
set_property PACKAGE_PIN AA26 [get_ports {fx3_db[7]}]
set_property PACKAGE_PIN AD22 [get_ports {fx3_db[8]}]
set_property PACKAGE_PIN Y25 [get_ports {fx3_db[9]}]
set_property PACKAGE_PIN AD24 [get_ports {fx3_db[10]}]
set_property PACKAGE_PIN AC24 [get_ports {fx3_db[11]}]
set_property PACKAGE_PIN AB24 [get_ports {fx3_db[12]}]
set_property PACKAGE_PIN AC25 [get_ports {fx3_db[13]}]
set_property PACKAGE_PIN AG20 [get_ports {fx3_db[14]}]
set_property PACKAGE_PIN Y26 [get_ports {fx3_db[15]}]
set_property PACKAGE_PIN Y28 [get_ports {fx3_db[16]}]
set_property PACKAGE_PIN AJ24 [get_ports {fx3_db[17]}]
set_property PACKAGE_PIN W29 [get_ports {fx3_db[18]}]
set_property PACKAGE_PIN W28 [get_ports {fx3_db[19]}]
set_property PACKAGE_PIN AK25 [get_ports {fx3_db[20]}]
set_property PACKAGE_PIN Y23 [get_ports {fx3_db[21]}]
set_property PACKAGE_PIN Y24 [get_ports {fx3_db[22]}]
set_property PACKAGE_PIN AK20 [get_ports {fx3_db[23]}]
set_property PACKAGE_PIN AK23 [get_ports {fx3_db[24]}]
set_property PACKAGE_PIN Y20 [get_ports {fx3_db[25]}]
set_property PACKAGE_PIN Y21 [get_ports {fx3_db[26]}]
set_property PACKAGE_PIN AF21 [get_ports {fx3_db[27]}]
set_property PACKAGE_PIN AA21 [get_ports {fx3_db[28]}]
set_property PACKAGE_PIN AH25 [get_ports {fx3_db[29]}]
set_property PACKAGE_PIN AG25 [get_ports {fx3_db[30]}]
set_property PACKAGE_PIN AK24 [get_ports {fx3_db[31]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fx3_db[*]}]

set_property PACKAGE_PIN AJ23 [get_ports {fx3_a[0]}]
set_property PACKAGE_PIN AF22 [get_ports {fx3_a[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {fx3_a[*]}]

set_property PACKAGE_PIN AG23 [get_ports fx3_pclk]
set_property IOSTANDARD LVCMOS18 [get_ports fx3_pclk]
set_property PACKAGE_PIN H20 [get_ports FX3_RESET]
set_property IOSTANDARD LVCMOS18 [get_ports FX3_RESET]
set_property PACKAGE_PIN AA20 [get_ports FX3_SCL]
set_property IOSTANDARD LVCMOS18 [get_ports FX3_SCL]
set_property PACKAGE_PIN AB20 [get_ports FX3_SDA]
set_property IOSTANDARD LVCMOS18 [get_ports FX3_SDA]

set_property PACKAGE_PIN AD23 [get_ports fx3_flaga]
set_property IOSTANDARD LVCMOS18 [get_ports fx3_flaga]
set_property PACKAGE_PIN AG22 [get_ports fx3_flagb]
set_property IOSTANDARD LVCMOS18 [get_ports fx3_flagb]
set_property PACKAGE_PIN AH22 [get_ports fx3_flagc]
set_property IOSTANDARD LVCMOS18 [get_ports fx3_flagc]
set_property PACKAGE_PIN AJ22 [get_ports fx3_flagd]
set_property IOSTANDARD LVCMOS18 [get_ports fx3_flagd]
set_property PACKAGE_PIN AK21 [get_ports fx3_slcs_n]
set_property IOSTANDARD LVCMOS18 [get_ports fx3_slcs_n]
set_property PACKAGE_PIN AH21 [get_ports fx3_slwr_n]
set_property IOSTANDARD LVCMOS18 [get_ports fx3_slwr_n]
set_property PACKAGE_PIN AH20 [get_ports fx3_sloe_n]
set_property IOSTANDARD LVCMOS18 [get_ports fx3_sloe_n]
set_property PACKAGE_PIN AE20 [get_ports fx3_slrd_n]
set_property IOSTANDARD LVCMOS18 [get_ports fx3_slrd_n]
set_property PACKAGE_PIN W27 [get_ports fx3_pktend_n]
set_property IOSTANDARD LVCMOS18 [get_ports fx3_pktend_n]

set_property SEVERITY {Warning} [get_drc_checks NSTD-1]

set_property SEVERITY {Warning} [get_drc_checks UCIO-1]